"""empty message

Revision ID: 49e38214ac6c
Revises: 20ae57a2f067
Create Date: 2022-03-17 17:21:10.777356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e38214ac6c'
down_revision = '20ae57a2f067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'is_admin')
    # ### end Alembic commands ###
